language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@latest
install: npm install
script: npm test
before_deploy: npm run build
deploy:
  provider: heroku
  api_key:
    secure: BYzUfUOH4l2hrTWTue2Zg18IffMJ3UrdOXELK41+T9qePqQjJfwVNzwrV8MMdWBaCYpoQm7PMSUoqcx/hFVvK7wlDWbaaoSqySfUcI0VWssshC/8PsuhkTZe8iI2/rA/MeO3QH/rjX0HTnhNFq4u5H2VWIj6CJOUXdfqI+n5YVz1hmwkqpAm9khJPblOB/t8bVNk1L2pESo4pH6fMTrCat3X/bb2eNB+TfdIkIWtd0q3aLxoerHd2mxr8SFewrD8Lh3rp7RXOXZwWhrNyBhrj6kC9J8UuMgJ0ACitiTFrlbIwa5reo/9uM9fRB1TlHqJFDcHjuftiMQUjpOLE039rGe4IleGGzL3mAF7LQoF2/CwtayAtHeIVkdBXt8nkyQBwOKxT6spk9r0ZweB5lyb87Hf95Z1FHe70Ws/Wnxrw5wXAuxjy3KYmsiOFOih6m+H5ef1lRWiIybJkeY1VK78FDAF4UtoAjAfQe+6yUbFZ7YobIvljY5TNcnCVTvNSGgQjAE5d/gQzLlsnKoNRsueT8W4T9CfN5jM9hgC1VoBM5te0Gjv+hjU+48s5Yi6HFiS4Rlt0buM+Fb8XW3ebcK59vxGZYKB3voQW3oet2GDELnC6gfOhSAd9WYysSrS5KdVIVlzBANI27uRi1dwrbr1CkSP9HrdpHaRZAECuYTJVe0=
    app: https://evening-chamber-45171

