language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@latest
install: npm install
script: npm test
before_deploy: npm run build



deploy:
  provider: heroku
  api_key:
    secure: KRipYMEDNC6jGBH/6RMoROcj98H8R9eJ3xXG/G++sux5WBfd/CMByUAWsTAPTby8tuOXUZExkS7UQk/O71Wlk6JAFbiHjlmmkpAZw8xK/pyW7pz/3QzKmbAf9QiIinAOdgr0O6cFuBgCANdZdqI1TvwnLsFRmftIRGirHrZHFE5gJMpWp2SCM/kAO/KE+jtjCeR6UnX8V/O2S71k9eTTp4Wlzvh9sUZDRITkXSAT1EdTR6EPsZnvw0pnMOO5DyFYlXqceyCEX782y1xrs95/AooVx2HmgtxjqeHTU2vWKp9oC/aHCHmiFg5ybJ1dO0cn0H8CuDyZXI4v7WVQJVmdeIVm4ZrdAWhcbJd8AAumtiOAbwrAzhuHAlD2/1REqWOBsJClZ/wgY9mVIR88Jd63OByaiLejJw7NfKnyRGlxc2KR2oltkRs6muIEYBXtCikPO8781EC7wdiUGpKBNbVNncU+9Dk5+kMHxOS5vb4hFN7SwH2Bv0zbTxrdYrk9eUfkc4tra5vFsbOhIIN2xON/gG1nqkDJR++Mrboo7yrUalCDszhV185bFE2rxHZW3TeRYNLV0JIcT5t+QL1SwQxQo18GJrYEv4KtX3DIFbaDQfcy+tsbv6itYli17yvZQhicYmL82QSdidN1VD+69i+wIArwFaDU/0mAkbOuOPKfDfA=
  app: evening-chamber-45171