language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@latest
install: npm install
script: npm test
before_deploy: npm run build
deploy:
  provider: heroku
  api_key:
    secure: XZBAk+fg7GHnaAG4ycDhcglp0wZGh/NZvILOUFmHdc3KQ2kW11Dqnfb8+rbVuU8EQJSGgTM51Ds+mv+I6E6MUDhZ0vQH/Z8otef2eczzisQaonfH7N1/lRzhvKp+VtKfNXp7qhhYnHDAfxfa9N3ob7iNEpMjfaOhmMpccxwjIt/K99AnO90cytqFahzWotkCY2+nxoo/TAHsPG9cd9Cozg+Bvp/+YNOH0Bn9wsAqAYFQAEMkAgZrl6Uy+yZ9A64ABoPIKQz9mI/HCfPKM+wOSfkqrvi+FS6Lw/nNVEPwrxwpGW6K7QW66/iDISsLxHXw46ZoxVmdTBiODhirgi8Mr0LkXuRbQNpQg0GQs1BydkXScWObZV+yHJ3aBHUJTcWed7Jjk8MqXT1oNPWrx4EhAFg+H0WeB+8KkpbwBJDV6ebky2+jKH+zuOeyrits9LF9L1KOk4/uS1ZMevCyNqaZ1MoD+BC9olEYoC1xRUCBSGj11tRf0o0mNwLelh9aS1dP6udOqkkLphejSOAVNausvBlvXr1XP/7X83MDlIrWGAhMOntJTb/9hiqGkLRmYUup4GDlR58Noj3smxreY1nXV7KtAlJHc4CAguL1/yJirPSs+un/RyG5R1DBlKObZG37RNlGijugoiRttV7OcPsehxoktahBHEY6tfV91qBgOVI=
  app: otaspa
  on:
    repo: MrRisoni/otaspa
