language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@latest
install: npm install
script: npm test
before_deploy: npm run build



deploy:
  provider: heroku
  api_key:
    secure: xkjVfNnM7QtNVGMscTdKDTq5mA4QtWBEiRsngceT6YB0dGV9fb7Yx40madfPHOh3uDr3JkM4Pu+VKe6kQVOZNfdR22G3GiTJxWUKVx5ADek6ewN96wdHuaxcTFJhv3FpeL/uTXVZGBoI8zQvvXn0yS5Jj6k6968w6aLei6pablYRkIflCKR7ZOTd7H3LTepKlhnHuPQoD7vn8ri38yBfy5OuRJK0AAr2mcwztaBbcPXPZJG/2e9rOlKxd6T8CEYyl7Mco42wlGViA/rmDbhr9f2hwB5Cpj71yxdnh7hLgTbSeMmGPJO/MNuPU1tvAOm40gUVg/s+jWQdH0WlLlMDcCJP1JfcBWufDCmThfDlnEGqynwjJRpsQ/OKm/KiRcu30eF/IxoMPwyyhO+9nCmYJMjUju2OeeSBi7h9mDKCx/4U3zE4Qcm6LyHQJe1UpqtwkzmR1NYG7Uq0wwjYeDvB9VmVThPj16m31hqe+hflWXiiYz6BAmHPaPtLugGllvBQQpqdCnzghm6pw66WtozJLKrAqDJgi7T3a4ZlX1H3PHp9jHEQzlNeA+ByIKPuwNfd6NDoiBUnnsbLrU2IPZGlbXBvHNmyWtI9SuNCP+8R7BYvhzcdu1Q8yEs/WhQnV8SahfYcftSH1QIbjxzSrA9UKKowEzht8/2BxT+zX8rwTGI=
  app: evening-chamber-45171